openapi: 3.0.0
info:
  title: Swagger Statistics Tennis Players
  description: The swagger Statistics Tennis Players server.
  version: 0.0.2
servers:
  - url: /api/statistics/tennis
paths:
  /player/players:
    get:
      summary: List all players by Rank
      operationId: getListPlayersByRank
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayerDTO'
  /player/{playerId}:
    get:
      summary: Info for a specific player
      operationId: getPlayerById
      parameters:
        - name: playerId
          in: path
          description: player id
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerDTO'
  /statistics/players:
    get:
      summary: Info for a specific statistics (IMC average, mediane of height players, country with most ratio win ...)
      operationId: getStatistics
      responses:
        200:
          description: map of statistics
          content:
            application/json:
              schema:
                $ref: '#/definitions/statistics'
components:
  schemas:
    statistics:
      type: object
      additionalProperties:
        type: string
    PlayerDTO:
      type: object
      description: player info
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
        lastname:
          type: string
        shortname:
          type: string
        sex:
          type: string
        picture:
          type: string
        country:
          $ref: '#/definitions/CountryDTO'
        data:
          $ref: '#/definitions/DataDTO'
    CountryDTO:
      type: object
      properties:
        picture:
          type: string
        code:
          type: string
    DataDTO:
      type: object
      properties:
        rank:
          type: integer
          format: int32
        points:
          type: integer
          format: int32
        weight:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        age:
          type: integer
          format: int32
        last:
          type: array
          items:
            type: integer
            format: int32